name: Publish tag

on:
  push:
    tags:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: chmod gradlew
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: list file build.
        run: ls -al build/libs

      - name: rename file
        run: mv build/libs/excel_enscrypt* build/libs/excel_enc.jar

      - name: list file build.
        run: ls -al build/libs

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/excel_enc.jar
          asset_name: excel_enc.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "jar file"